# Generated by Django 4.1.4 on 2022-12-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_auctionlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='currentPrice',
            field=models.IntegerField(default=models.IntegerField()),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
