# Generated by Django 4.1.4 on 2022-12-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlisting_currentprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='currentPrice',
        ),
    ]
