# Generated by Django 4.1.4 on 2022-12-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auctionlisting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
