# Generated by Django 4.1.4 on 2023-01-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='auctions.auctionlisting'),
        ),
    ]
